package com.tgame.extraperception;

import com.tgame.extraperception.armor.ItemShamanArmor;
import com.tgame.extraperception.casting.CastTickEventListener;
import com.tgame.extraperception.proxies.CommonProxy;
import com.tgame.extraperception.utils.ESPCreativeTab;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;
import net.minecraftforge.common.MinecraftForge;

/**
 * @since 21/04/14
 * @author tgame14
 */
@Mod(modid = Settings.MODID, version = Settings.VERSION, name = Settings.NAME)
public class ExtrasensoryPerception
{
    @Mod.Instance(Settings.MODID)
    public static ExtrasensoryPerception instance;

    @SidedProxy(serverSide = "com.tgame.extraperception.proxies.CommonProxy", clientSide = "com.tgame.extraperception.proxies.ClientProxy")
    public static CommonProxy commonProxy;

    @Mod.Metadata
    private static ModMetadata metadata;

    public static Item itemShamanHelmet;
    public static Item itemShamanChest;
    public static Item itemShamanLegs;
    public static Item itemShamanBoots;

    private static void registerItem(Item item)
    {
        GameRegistry.registerItem(item, item.getUnlocalizedName().replace("item.", ""));
        item.setCreativeTab(ESPCreativeTab.INSTANCE);
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        itemShamanHelmet = new ItemShamanArmor(commonProxy.addArmor("shaman"), 0);
        itemShamanChest = new ItemShamanArmor(commonProxy.addArmor("shaman"), 1);
        itemShamanLegs = new ItemShamanArmor(commonProxy.addArmor("shaman"), 2);
        itemShamanBoots = new ItemShamanArmor(commonProxy.addArmor("shaman"), 3);

        registerItem(itemShamanHelmet);
        registerItem(itemShamanChest);
        registerItem(itemShamanLegs);
        registerItem(itemShamanBoots);

        MinecraftForge.EVENT_BUS.register(new CastTickEventListener());
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event)
    {
        metadata.authorList.add("@AUTHOR@");
        metadata.autogenerated = false;
        metadata.modId = Settings.MODID;
        metadata.name = Settings.NAME;
        metadata.description = "The human mind has abilities we were not able to use, Until now, find out what you can do, with only yourself, and your head";
        metadata.version = Settings.VERSION;
        metadata.credits = "@AUTHOR@";

    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {

    }



}
